### ISSUE TITLE
SIA in plaats van SIG

### ISSUE THREAD

**Issue by arvidsmits** [Signalen/product-steering#143]

**Comment by someren** [comment]
Getest, nog niet opgelost.

**Comment by someren** [comment]
Niet opgelost in versie 2.5, getest op accp 's-Hertogenbosch:
![image](https://user-images.githubusercontent.com/66589775/177982543-da316360-d7ae-4eb5-95c1-572e8e8f7688.png)

**Comment by someren** [comment]
Volgens mij hebben we nu versie 2.6.2 op accp 's-Hertogenbosch:
![image](https://user-images.githubusercontent.com/66589775/178423258-86cda7e5-d988-41e9-841f-bae6d0ad67b3.png)

**Comment by someren** [comment]
Opgelost in versie 2.7 / 2.6.2
![image](https://user-images.githubusercontent.com/66589775/180410355-1d0bc9d3-da48-4d09-ae77-c7824e3a40a7.png)
