### ISSUE TITLE
BE Bijlage: In de geschiedenis staat ‘notitie toegevoegd’ met het email adres van degene die het heeft toegevoegd (niet Signalen systeem).

### ISSUE THREAD

**Issue by arvidsmits** [Signalen/product-steering#176]

**Comment by tcoenen** [comment]
Dit is niet mogelijk omdat bij het verwijderen van een attachment de attachment dan ook uit de geschiedenis zou vallen, vandaar de keus om met notities te werken. Dit is iets wat op te lossen is nadat we het geschiedenis systeem van Signalen aangepast hebben.

Ik raad sterk af om hier de release op te blokkeren!

**Comment by tcoenen** [comment]
Gemergde PR: https://github.com/Amsterdam/signals/pull/1001/files <- Als een gebruiker een attachment toevoegt of verwijdert dan wordt die gebruiker niet meer genoemd in tekst in de geschiedenis. In plaats daarvan staat de gebruiker in de linker kolom.

**Comment by someren** [comment]
Akkoord. Getest op versie 2.7.1 acceptatieomgeving VNG.
