### ISSUE TITLE
BUG: bij Geen rechten op contactgegevens staan de gegevens wel in de pdf

### ISSUE THREAD

**Issue by arvidsmits** [Signalen/product-steering#184]

**Comment by tcoenen** [comment]
Willen we verhaspelde contactgegevens zoals in emails of willen we ***** zoals in de API?

**Comment by tcoenen** [comment]
Is al vorige week gemergd naar master, release moment nog niet bekend.

**Comment by someren** [comment]
Akkoord, getest op acceptatieomgeving VNG. Versie 2.7.1.
