### ISSUE TITLE
BUG: Foto in PDF bestand valt deels weg

### ISSUE THREAD

**Issue by arvidsmits** [Signalen/product-steering#193]

**Comment by someren** [comment]
Voorbeeld (ACCP Common ground melding nummer 68):
![image](https://user-images.githubusercontent.com/66589775/181461544-049a4824-978c-44c4-ba0b-86f382d9c2ed.png)

Gebeurd iedere keer bij deze foto maar niet als enige. Bij deze foto gebeurd het ook:
![image](https://user-images.githubusercontent.com/66589775/181462275-09f9dd99-9587-4e7c-8ef8-966b5254beca.png)

**Comment by tcoenen** [comment]
De foto's zijn heel smal en hoog. Waarschijnlijk vallen de onderkanten van de foto's van de pagina af. Misschien op te lossen in print CSS.

**Comment by tcoenen** [comment]
Voorgestelde fix in layout:

[example-image-layout.pdf](https://github.com/Signalen/product-steering/files/9229050/example-image-layout.pdf)

**Comment by tcoenen** [comment]
Na feedback VNG:

[example-new-image-layout-no-gray-backgrounds.pdf](https://github.com/Signalen/product-steering/files/9234153/example-new-image-layout-no-gray-backgrounds.pdf)

**Comment by someren** [comment]
Akkoord. Getest op acceptatieomgeving VNG versie 2.7.1
