### ISSUE TITLE
BUG: Op telefoon valt de knop “Notitie toevoegen” deels van het scherm af. Naar rechts slepen werkt niet.

### ISSUE THREAD

**Issue by someren** [Signalen/product-steering#195]

**Comment by boris-arkenaar** [comment]
Kan dit niet reproduceren op https://s-hertogenbosch.signalen.dev/
Tevens is dit wellicht gefixt na de attachments feature.

**Comment by someren** [comment]
Akkoord. Getest op de acceptatieomgeving VNG, versie 2.7.1
