### ISSUE TITLE
Kolommen in Django zijn weggevallen

### ISSUE THREAD

**Issue by arvidsmits** [Signalen/product-steering#211]

**Comment by arvidsmits** [comment]
<img width="1279" alt="Schermafbeelding 2022-06-29 om 19 14 15" src="https://user-images.githubusercontent.com/78912649/176497304-d93fc76d-ed53-49ef-94da-7db33de45372.png">

**Comment by arvidsmits** [comment]
Kolom omschrijving en servicebelofte hetzelfde als is actieve en public accessible. Als die is ingevuld dan groen, anders rood.

**Comment by someren** [comment]
En bij Gebruikers is de afdeling weggevallen. Is door Cuong toegevoegd onder https://github.com/Signalen/product-steering/issues/78
