### ISSUE TITLE
Reactie gevraagd na 5 dagen automatisch naar reactie ontvangen - zie Amsterdam

### ISSUE THREAD

**Issue by arvidsmits** [Signalen/product-steering#237]

**Comment by tcoenen** [comment]
Probleem is de scheduling die in Amsterdam via Jenkins gebeurt. Jenkins is niet beschikbaar voor VNG installaties (en in de toekomst ook niet voor Amsterdam). Periodieke taken in VNG installaties kunnen vanuit de applicatie gedraaid worden of gescheduled via Kubernetes.

Kort overleg gehad over de twee mogelijkheden, uitkomst is dat we de periodieke taken draaien vanuit de applicatie en ook aanstuurbaar maken via management commando's. We maken ook een script waarmee de standaard periodieke taken toegevoegd worden aan de database. Dat laatste wordt een andere ticket.

**Comment by tcoenen** [comment]
Aanpassing in Signalen is gemergd wordt deel van release 2.7.1 of 2.8.0. Nadat dit is uitgerold kunnen functioneel beheerders of systeem beheerders de periodieke taak aanzetten.

**Comment by someren** [comment]
Akkoord. Getest op acceptatieomgeving VNG, versie 2.7.1
