### ISSUE TITLE
Statussen niet in de code, maar in een tabel in de database opnemen

### ISSUE THREAD

**Issue by edjverhoeven** [Signalen/product-steering#247]
## Gegevens aanvrager

Gemeente: Bergen op Zoom
Naam indiener: Erik Verhoeven
Telefoonnummer(optioneel): 
E-mailadres: e.d.j.verhoeven@bergenopzoom.nl

### Omschrijving
Het zou mooi zijn wanneer de statussen van meldingen niet hardcoded geprogrammeeerd zijn, maar netjes in een tabel worden opgenomen.
Hierdoor hoef je bovendien bij het toevoegen van statussen geen rekening meer te houden met het aanpassen van view signals_ext_tdo.
https://github.com/Signalen/backend/issues/173

**Comment by bartjkdp** [comment]
Wordt opgepakt in https://github.com/Signalen/backend/issues/173, daarom kan deze dicht.
