### ISSUE TITLE
's-Hertogenbosch: WFS service met MOON

### ISSUE THREAD

**Issue by someren** [Signalen/product-steering#248]
Openbare verlichting leverancier MOON is bezig met een WFS service om objecten op de kaart te tonen.
Zij hebben nog enkele vragen, met wie kunnen zij contact opnemen?

1. Kunnen jullie zelf een WFS url invoeren in de instellingen of is dat iets wat Signalen moet doen? En kan dat op test makkelijk worden gedaan? --> Kan ik (Amy) denk ik zelf met de juiste (publieke) url?
2. Hoe ziet de invoer/info van stap 1 er dan uit? Dit omdat WFS vele soorten data kunnen omhelzen.. bij Amsterdam zie ik dat ze nu kiezen voor een json output (ook onze voorkeur overigens)
3. In de data van Amsterdam zie ik allerlei type definities ivm het tonen van een icoon, is daar een lijst van beschikbaar?
4. Voorbeeld output van Amsterdam, de meeste onderdelen kunnen we goed matchen aan moon id’s en namen uiteraard, maar ik zie een aantal zaken waar niet helemaal duidelijk is wat er wordt verwacht.
Wie zou deze vragen kunnen beantwoorden?

{
"type": "Feature”,
 
"id": "openbareverlichting.71978”,
"geometry_name": "101444”,
"geometry": {
"type": "Point",
"coordinates": [4.89038200003727, 52.37279700466]
},
"properties": {
"id": 71978,
"object_id": "84026",
"objecttype": "4",
"objecttype_omschrijving": "LSD Objecten",
"objectnummer": "101444",
"breedtegraad": 52.3727970209456,
"lengtegraad": 4.89038242738189,
"storingstatus": 0,
"meldingstatus": 0
}
}

**Comment by tcoenen** [comment]
Deze vragen moeten gesteld aan Boris / onze frontend onwikkelaars. Vragen over de inhoud van de Amsterdamse WFS moeten gesteld aan de Amsterdamse frontend ontwikkelaars en als zij het niet weten team data services van Datapunt Amsterdam.

**Comment by boris-arkenaar** [comment]
1. Dat kan je inderdaad zelf doen in de Django Admin bij het invoeren van een extra vraag. Zie https://github.com/Signalen/frontend/blob/develop/docs/additional-questions.md voor uitleg. Volg `AssetSelect` voor het type extra vraag dat dient voor het selecteren van assets op de kaart.
2. Wat bedoel je met stap 1?
3. De bestaande icoontjes die Amsterdam gebruikt kan je hier vinden: https://github.com/Signalen/frontend/tree/develop/assets/images
4. Ik weet niet zeker wat je bedoelt. Als je een WFS hebt is het minimale wat je nodig hebt in de `properties` van een object, een 'ID' en een 'type'. In de instellingen van de extra vraag kan je opgeven hoe die velden precies heten.

**Comment by someren** [comment]
Dankjewel Boris! Ik heb het doorgegeven aan MOON. Eens kijken hoe ver we komen.

**Comment by someren** [comment]
Antwoorden waren duidelijk voor leverancier. URL is opgeleverd maar lopen tegen content security policy aan. Hiervoor melding #303 aangemaakt.
