### ISSUE TITLE
's-Hertogenbosch: Ondersteuning berichten van MOON via Signalen naar melder

### ISSUE THREAD

**Issue by someren** [Signalen/product-steering#249]
Wanneer een melding in MOON van status wijzigt, dan wijzigt MOON de status van de melding in Signalen en voegt een notitie toe. Bij sommige statuswijzigingen zoals naar "Ingepland" in Signalen zou er een bericht naar de melder gestuurd moeten worden. Omdat de e-mail bij deze statuswijziging optioneel is, wordt er momenteel geen e-mail verstuurd. In het bericht wat MOON naar Signalen stuurt moet dus 'iets' worden toegevoegd waardoor er ook een e-mail naar de melder gaat. 

Hoe kan dit gerealiseerd worden?

**Comment by tcoenen** [comment]
Als de status gepatcht wordt, en alleen voor statussen waar je een email mag versturen kun je `"send_email": true` toevoegen aan het PATCH bericht. Voorbeeld voor status wijziging (PATCH op detail endpoint) naar GEMELD:

```
{
  "state": "m",
  "text": "test stuur email",
  "send_email": true
}
```

In plaats van:
```
{
  "state": "m",
  "text": "test stuur geen email",
  "send_email": false
}
```

Dit betekent overigens wel dat MOON rechtstreeks contact heeft met de melder.

**Comment by someren** [comment]
Dankjewel Thijs! Ik heb het doorgegeven aan MOON. Wacht nu de testbevindingen af :)

**Comment by someren** [comment]
Testbevindingen zijn positief, berichten worden nu verstuurd.
