### ISSUE TITLE
Huidige (publieke) kaart om de categorieën wel eruit te filteren

### ISSUE THREAD

**Issue by Astrid-Utrecht** [Signalen/product-steering#301]
Gemeente: Utrecht
Naam indiener: Astrid
Telefoonnummer(optioneel):
E-mailadres: astrid.brantjes@utrecht.nl

Op subcategorie instelbaar maken publiek toegankelijke/niet toegankelijke meldingen. 

Bij het testen voor het live zetten van de openbare kaart liepen wij tegen deze issue aan. Op dit moment kan per subcategorie worden ingesteld of een (sub) categorie wel of niet publiek toegankelijk is. Daarbij kan ook een publieke naam worden meegegeven. Op dit moment worden de (sub) categorieën welke niet getoond mogen worden op de kaart in verband met bescherming van de melders/inwoners niet uit de te tonen meldingen gefilterd. Hierdoor kunnen we de data nog niet openbaar maken.

Dus:
(sub)categorie waarbij is weergegeven melding NIET publiek toegankelijk niet weergeven op de publiek toegankelijke kaart
Informatie op de publieke kaart met publieke naamgeving

Deze issue heeft een erg hoge prio voor Utrecht om de data op een veilige manier publiek toegankelijk te maken op de huidige kaart.

**Comment by bartjkdp** [comment]
Het endpoint dat door deze (oude) kaart gebruikt wordt, is gemarkeerd als "te verwijderen" in de backend. Bij navraag wordt deze kaart uitgefaseerd bij Gemeente 's-Hertogenbosch. Een mooie kans dus om deze kaart (en oude code in de backend) helemaal te verwijderen, mits de nieuwe kaart voldoet aan de wensen van Utrecht.

Sinds (zeer) kort is de nieuwe kaart beschikbaar, waardoor Utrecht deze wellicht direct kan gebruiken. Deze kaart filtert wel de niet publiek toegankelijke categorieën. Ik heb 'm net uitgerold op de testomgeving zodat we hier mee kunnen testen.

**Comment by bartjkdp** [comment]
Probleem is opgelost door gebruik te maken van de nieuwe kaart.
